[package]
name = "example-with-output"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor_client_gen = { path = "../anchor-client-gen", package = "anchor_client_gen" }
anchor-lang = { version = "0.28.0" }
bytemuck = { version = "1.4.0", features = ["derive", "min_const_generics"] }
